services:
  mongo:
    image: mongo:6.0.26
    container_name: mongo
    restart: "no"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: productos

volumes:
  mongo_data:
